### PR TITLE
feat(binary_sensors): adding in door, window and lock binary sensors

### PR DESCRIPTION
**Pull request by stephengolub**
First "SWAG" at binary sensors, per #7

### CODE REVIEW

**Review by vanstinator — COMMENTED** [review]
I wonder if we should abstract some of this better in the pip library before trying to do this here.

**Comment by widewing** [comment]
This probably not gonna work: https://github.com/widewing/ha-toyota-na/issues/7#issuecomment-1016134445

**Comment by stephengolub** [comment]
If you look at the code, it's not using that endpoint. It's using your existing endpoint to get the binary sensors.

**Comment by stephengolub** [comment]
> I wonder if we should abstract some of this better in the pip library before trying to do this here.

Also probably a better idea. You'd have less text parsing down stream.

**Comment by vanstinator** [comment]
I started working on a vehicle class yesterday precisely to handle the parsing. I'll have a PR in a day or two for some feedback

**Pull request closed without merging**
