### PR TITLE
Fix API Domain

### PR DESCRIPTION
**Pull request by seang96**
This is a fix for #99. I tested this and added my changes through github since I did this mobile. Please validate and check yourself aswell since I am also using a different brand.

### CODE REVIEW

**Comment by widewing** [comment]
it seems your committed file was striped at 64 characters each line?

**Comment by seang96** [comment]
Ah yeah doing this on mobile sucks... I'll fix that real quick.

**Comment by widewing** [comment]
and I think you need to actually patch the method in __init__.py

**Comment by seang96** [comment]
Good catch. Added it, I already had that patched to override the brand so I didn't think of it for the PR.

**Pull request merged**
