### PR TITLE
Fix for unsubscribed users

### PR DESCRIPTION
**Pull request by Rouble**
This continue prevented all the sensors that don't require a subscription from being added in home assistant

### CODE REVIEW

**Comment by Rouble** [comment]
fixes the problem mentioned in the comments on several issues after the 2.5 update where users with an "UNKNOWN" subscription status have no entities added in home assistant

**Comment by bmitchell76** [comment]
Thanks for all your effort, I was hopeful but unfortunately, I'm now hitting a different issue.

No devices or entities
Failed setup, will retry: 400, message='Bad
Request', url='https://oneapi-
east.telematicsct.com/v1/global/remote/ref
resh-status'

I've tried to remove the integration, remove it from HACS, restart, add it back to HACS, reboot, and add the integration.  I'm able to sign in but get the error above when it tries to create the integrations.

In a browser I'm unable to access...

http://east.telematicsct.com/v1/global/remote/ref

...the site can't be reached.

**Comment by bmitchell76** [comment]
I take that back, I can access…

https://oneapi-east.telematicsct.com/v1/global/remote/ref

…in a browser.

{
 "status": {
   "messages": [
     {
       "responseCode": "APIGW-403",
       "description": "Unauthorized",
       "detailedDescription": ""
     }
   ]
 }
}

**Comment by Rouble** [comment]
This seems unrelated to the issue i fixed. You may want to open an issue for this if you haven't already

**Comment by Rouble** [comment]
On second thought, it might be tangentially related. I've never been able to get the refresh action to work so i suspect it's a subscriber only feature. Might need to add a subscription check before trying to do the refresh that can now happen with the change i made.

**Pull request merged**
